# Generated by Django 4.1.7 on 2023-04-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_media_name_alter_portfolio_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactprofile',
            options={'ordering': ['timestamp'], 'verbose_name': 'Contact Profile', 'verbose_name_plural': 'Contact Profiles'},
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to="certificate_images/'"),
        ),
    ]
